#!/data/data/com.termux/files/usr/bin/bash

losetup -l /dev/block/loop777 2> /dev/null | grep slackwarefs.img > /dev/null

if [ $? = 0 ]
then
    echo 'Disk telah diatur!'
else
    echo 'Mengatur disk,...'
    losetup --partscan /dev/block/loop777 /storage/sdcard1/rootfs/slackwarefs.img
    echo 'OK!'
fi

if [ -e ~/slackware/root ]
then
    echo 'Disk telah ditautkan!'
else
    echo 'Menautkan disk,...'
    /system/bin/mount -w -t ext4 /dev/block/loop777p1 ~/slackware
    echo 'OK!'
fi

unset LD_PRELOAD

proot --link2symlink -0 -r ~/slackware -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b $HOME -w /root /bin/env -i HOME=/root TERM="$TERM" PS1='[termux@slackware \W]\# ' LANG=$LANG PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login
